### ISSUE TITLE
Request for datasets

### ISSUE THREAD

**Issue by lizhou21** [vinid/not-just-hate#1]
Hi, I'm very interested in your work. Can you provide your dataset? The dataset I downloaded from the OSF website has no data description and looks incomplete, only label.

Looking forward to your reply.

**Comment by vinid** [comment]
Hello!

the data shared contains tweet ids and labels. Due to Twitter guidelines we cannot share the text directly, you need to reconstruct the tweet yourself. 

Let me know if you have further questions!

**Comment by lizhou21** [comment]
Thank you for your reply, 
I see that there are many columns in the datasets, 
can you provide a README file to describe the information in the datasets, 
so as to prevent my wrong understanding for these columns?

**Comment by vinid** [comment]
You are right that is something I have to do. In the meantime, the most important column to consider should be the following:

```tweet_id``` to reconstruct the tweet

and

```
'Aggregated - Incivility - Insults',
'Aggregated - Incivility - Character Assassination',
'Aggregated - Incivility - Outrage',
'Aggregated - Hostility - Hateful Speech',
'Aggregated - Hostility - Dehumanisation',
'Aggregated - Hostility - Serious Threat, Personal Abuse & Harassment',
'Aggregated - Discrimination',
'Aggregated - Hostility - Democratic Threat',
```

These are the aggregated annotations (the other columns mainly refer to the score of specific annotators) and corresponds to the labels described in the paper. Note that **in the paper** the following four labels

```       
'Aggregated - Discrimination',
'Aggregated - Hostility - Democratic Threat',
'Aggregated - Hostility - Serious Threat, Personal Abuse & Harassment',
'Aggregated - Hostility - Hateful Speech',
```
are aggregated in a single label referred to as **Hostility**. You'll find information about this at the end of the paper.

Let me know if you have additional questions! Happy to help!

**Comment by lizhou21** [comment]
> 

Thank you very much for your help
